# Generated by Django 3.0.4 on 2020-03-09 19:34

import Board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FilePathField(blank=True, path=Board.models.images_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='pose_status',
            field=models.CharField(choices=[('1', 'Post Opened'), ('2', 'Post Closed')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('1', 'buyer'), ('2', 'seller')], default='01', max_length=2),
        ),
    ]
