# Generated by Django 3.0.4 on 2020-03-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_auto_20200310_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pose_status',
            field=models.CharField(choices=[('1', 'Post Opened'), ('2', 'Post Closed')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('1', 'buyer'), ('2', 'seller')], default='1', max_length=2),
        ),
    ]
