# Generated by Django 3.0.4 on 2020-03-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_auto_20200310_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
