# Generated by Django 3.0.4 on 2020-03-10 06:45

import Board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0004_message_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FilePathField(blank=True, null=True, path=Board.models.images_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
